d = {}
ctr = 1
for i in range(15):
    d[ctr] = 15 - i
    ctr *= 2

for i in range(32768):
    ctr = 1
    if i not in d:

    for j in range(20):
        k1 = i*ctr % 32768
        if k1 in d:
            d[i] = k1
        ctr *= 2

print(d[1])
# n = int(input())
# a = [int(x) for x in input().split()]
# for i in a:
#     print(d[i % 32768], end=' ')

# "pegging",
# "latinasgw",
# "facesitting",
# "youtubersgonewild",
# "amazingtits",
# "yiff",
# "NSFW_HTML5",
# "streamersgonewild",
# "GirlswithNeonHair",
# "shorthairchicks",
# "stockings",
# "dykesgonewild",
# "WesternHentai",
# "sabrina_nichole",
# "agedbeauty",
# "erinashford",
# "SchoolgirlSkirts",
# "bigboobsgonewild",
# "porninaminute",
# "torpedotits",
# "breastenvy",
# "oldschoolcoolNSFW",
# "nsfw_plowcam",
# "twingirls",
# "legs",
# "justhotwomen",
# "tessafowler",
# "youtubetitties",
# "evalovia",
# "leggingsgonewild",
# "sexybutnotporn",
# "lactation",
# "Ohlympics",
# "TributeMe",
# "iWantToFuckHer",
# "socialmediasluts",
# "goneerotic",
# "nakedadventures",
# "oralcreampie",
# "celebritybutts",
# "furry",
# "puffies",
# "christiangirls",
# "breakingtheseal",
# "remylacroix",
# "forcedcreampie",
# "cumonclothes",
# "kpopfap",
# "feet",
# "LiyaSilver",
# "cosplaybutts",
# "gonewildchubby",
# "femalepov",
# "WtSSTaDaMiT",
# "shinyporn",
# "bikinis",
# "verifiedamateurs",
# "painal",
# "braceface",
# "fauxbait",
# "pussymound",
# "nsfwcostumes",
# "truefmk",
# "WeddingsGoneWild",
# "treesgonewild",
# "omgbeckylookathiscock",
# "hipcleavage",
# "collared",
# "gonewildhairy",
# "just18",
# "moundofvenus",
# "thicker",
# "onmww",
# "pulsatingcumshots",
# "gifsofremoval",
# "besthqporngifs",
# "onoffcelebs",
# "sashagrey",
# "onherknees",
# "Camwhores",
# "legalteensXXX",
# "NotSafeForNature",
# "tightshorts",
# "clothedtitfuck",
# "GiannaMichaels",
# "sexyflowerwater",
# "onstageGW",
# "dirtygaming",
# "rule34overwatch",
# "mmgirls",
# "tight_shorts",
# "nsfwfashion",
# "before_after_cumsluts",
# "volleyballgirls",
# "emilybloom",
# "cfnm",
# "nsfw_videos",
# "pawgtastic",
# "mycherrycrush",
# "coltish",
# "hopelesssofrantic",
# "militarygonewild",
# "girlsinschooluniforms",
# "presenting",
# "sweatermeat",
# "athleticgirls",
# "missalice_18",
# "lovetowatchyouleave",
# "gillianbarnes",
# "page3glamour",
# "bowsette",
# "realsexyselfies",
